// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyPlatform.Api.Data;

#nullable disable

namespace StudyPlatform.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928073649_AddFreePracticeStudySessionMode")]
    partial class AddFreePracticeStudySessionMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.ActivityAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivitySnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("AnswerJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptsUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FillBlankActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("FsrsRating")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrderingActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PresentationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecognitionActivityId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ResponseTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("FillBlankActivityId");

                    b.HasIndex("OrderingActivityId");

                    b.HasIndex("PresentationId")
                        .IsUnique();

                    b.HasIndex("RecognitionActivityId");

                    b.HasIndex("StudySessionId", "CreatedAtUtc");

                    b.HasIndex("StudentId", "ConceptId", "CreatedAtUtc");

                    b.ToTable("ActivityAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ActivityAttempts_ActivityReferenceMatchesType", "(\n    (\"ActivityType\" = 'TrueFalse' AND \"RecognitionActivityId\" IS NOT NULL AND \"FillBlankActivityId\" IS NULL AND \"OrderingActivityId\" IS NULL)\n    OR (\"ActivityType\" = 'FillBlank' AND \"RecognitionActivityId\" IS NULL AND \"FillBlankActivityId\" IS NOT NULL AND \"OrderingActivityId\" IS NULL)\n    OR (\"ActivityType\" = 'Ordering' AND \"RecognitionActivityId\" IS NULL AND \"FillBlankActivityId\" IS NULL AND \"OrderingActivityId\" IS NOT NULL)\n    OR (\"ActivityType\" IN ('Exposure', 'GuessConcept') AND \"RecognitionActivityId\" IS NULL AND \"FillBlankActivityId\" IS NULL AND \"OrderingActivityId\" IS NULL)\n)");

                            t.HasCheckConstraint("CK_ActivityAttempts_Attempts_Positive", "\"AttemptsUsed\" > 0");

                            t.HasCheckConstraint("CK_ActivityAttempts_Hints_NonNegative", "\"HintsUsed\" >= 0");

                            t.HasCheckConstraint("CK_ActivityAttempts_ResponseTime_NonNegative", "\"ResponseTimeMs\" IS NULL OR \"ResponseTimeMs\" >= 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("FillBlankActivities", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("FillBlankActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FillBlankActivityId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("FillBlankAnswers", null, t =>
                        {
                            t.HasCheckConstraint("CK_FillBlankAnswers_Slot_Positive", "\"SlotNumber\" > 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankDistractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FillBlankActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("FillBlankActivityId", "Text")
                        .IsUnique();

                    b.ToTable("FillBlankDistractors", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.OrderingActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("OrderingActivities", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.OrderingActivityItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderingActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderingActivityId", "Position")
                        .IsUnique();

                    b.ToTable("OrderingActivityItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderingActivityItems_Position_NonNegative", "\"Position\" >= 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.RecognitionActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("RecognitionActivities", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CodeNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Code\")", true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeNormalized")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Classrooms", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ClassroomModule", b =>
                {
                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClassroomId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("ClassroomModules", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ModuleId")
                        .HasName("AK_Concepts_Id_ModuleId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleId", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("Concepts", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptClue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId", "Position")
                        .IsUnique();

                    b.ToTable("ConceptClues", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConceptClues_Position_NonNegative", "\"Position\" >= 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId", "Value")
                        .IsUnique();

                    b.ToTable("ConceptKeywords", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptPrerequisite", b =>
                {
                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerequisiteConceptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("ConceptId", "PrerequisiteConceptId");

                    b.HasIndex("ConceptId", "ModuleId");

                    b.HasIndex("PrerequisiteConceptId", "ModuleId");

                    b.ToTable("ConceptPrerequisites", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConceptPrerequisites_NoSelfReference", "\"ConceptId\" <> \"PrerequisiteConceptId\"");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Modules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Modules_Version_Positive", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.SessionActivityPresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevealedClueCount")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("StudySessionId", "AnsweredAtUtc");

                    b.HasIndex("StudySessionId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("SessionActivityPresentations", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionActivityPresentations_RevealedClues_NonNegative", "\"RevealedClueCount\" >= 0");

                            t.HasCheckConstraint("CK_SessionActivityPresentations_Sequence_Positive", "\"SequenceNumber\" > 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrollmentNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TemporaryAccessCodeExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemporaryAccessCodeFailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("TemporaryAccessCodeHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId", "EnrollmentNumber")
                        .IsUnique();

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_TemporaryAccessCodeFailedAttempts_NonNegative", "\"TemporaryAccessCodeFailedAttempts\" >= 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.StudentConceptState", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ElapsedDays")
                        .HasColumnType("double precision");

                    b.Property<int>("FreeRecallSuccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("FsrsState")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("Lapses")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFailureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFreeRecallSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastFreeRecallSuccessSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastFsrsRating")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime?>("LastReviewAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearningState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("integer");

                    b.Property<double?>("ScheduledDays")
                        .HasColumnType("double precision");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision");

                    b.HasKey("StudentId", "ConceptId");

                    b.HasIndex("ConceptId");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("LastFreeRecallSuccessSessionId");

                    b.ToTable("StudentConceptStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentConceptStates_Difficulty_NonNegative", "\"Difficulty\" IS NULL OR \"Difficulty\" >= 0");

                            t.HasCheckConstraint("CK_StudentConceptStates_FreeRecallSuccessCount_NonNegative", "\"FreeRecallSuccessCount\" >= 0");

                            t.HasCheckConstraint("CK_StudentConceptStates_Lapses_NonNegative", "\"Lapses\" >= 0");

                            t.HasCheckConstraint("CK_StudentConceptStates_Repetitions_NonNegative", "\"Repetitions\" >= 0");

                            t.HasCheckConstraint("CK_StudentConceptStates_Stability_NonNegative", "\"Stability\" IS NULL OR \"Stability\" >= 0");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedActivities")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedConceptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StudentId", "ModuleId", "StartedAtUtc");

                    b.ToTable("StudySessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudySessions_ActivityCounts", "\"TotalActivities\" >= 0 AND \"TotalActivities\" <= 10 AND \"CompletedActivities\" >= 0 AND \"CompletedActivities\" <= \"TotalActivities\"");
                        });
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("lower(\"Email\")", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.ActivityAttempt", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("ActivityAttempts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.Activities.FillBlankActivity", "FillBlankActivity")
                        .WithMany("Attempts")
                        .HasForeignKey("FillBlankActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyPlatform.Api.Models.Activities.OrderingActivity", "OrderingActivity")
                        .WithMany("Attempts")
                        .HasForeignKey("OrderingActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyPlatform.Api.Models.SessionActivityPresentation", "Presentation")
                        .WithMany("Attempts")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyPlatform.Api.Models.Activities.RecognitionActivity", "RecognitionActivity")
                        .WithMany("Attempts")
                        .HasForeignKey("RecognitionActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyPlatform.Api.Models.Student", "Student")
                        .WithMany("ActivityAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.StudySession", "StudySession")
                        .WithMany("Attempts")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("FillBlankActivity");

                    b.Navigation("OrderingActivity");

                    b.Navigation("Presentation");

                    b.Navigation("RecognitionActivity");

                    b.Navigation("Student");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankActivity", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("FillBlankActivities")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankAnswer", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Activities.FillBlankActivity", "Activity")
                        .WithMany("Answers")
                        .HasForeignKey("FillBlankActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankDistractor", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Activities.FillBlankActivity", "Activity")
                        .WithMany("Distractors")
                        .HasForeignKey("FillBlankActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.OrderingActivity", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("OrderingActivities")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.OrderingActivityItem", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Activities.OrderingActivity", "Activity")
                        .WithMany("Items")
                        .HasForeignKey("OrderingActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.RecognitionActivity", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("RecognitionActivities")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Classroom", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Teacher", "Teacher")
                        .WithMany("Classrooms")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ClassroomModule", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Classroom", "Classroom")
                        .WithMany("ClassroomModules")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.Module", "Module")
                        .WithMany("ClassroomModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Concept", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Module", "Module")
                        .WithMany("Concepts")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptClue", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("Clues")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptKeyword", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("Keywords")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.ConceptPrerequisite", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("Prerequisites")
                        .HasForeignKey("ConceptId", "ModuleId")
                        .HasPrincipalKey("Id", "ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.Concept", "PrerequisiteConcept")
                        .WithMany("RequiredBy")
                        .HasForeignKey("PrerequisiteConceptId", "ModuleId")
                        .HasPrincipalKey("Id", "ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("PrerequisiteConcept");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Module", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Teacher", "Teacher")
                        .WithMany("Modules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.SessionActivityPresentation", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.StudySession", "StudySession")
                        .WithMany("Presentations")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("StudySession");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Student", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Classroom", "Classroom")
                        .WithMany("Students")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.StudentConceptState", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Concept", "Concept")
                        .WithMany("StudentStates")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.StudySession", "LastFreeRecallSuccessSession")
                        .WithMany("LastFreeRecallSuccessStates")
                        .HasForeignKey("LastFreeRecallSuccessSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StudyPlatform.Api.Models.Student", "Student")
                        .WithMany("ConceptStates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concept");

                    b.Navigation("LastFreeRecallSuccessSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.StudySession", b =>
                {
                    b.HasOne("StudyPlatform.Api.Models.Module", "Module")
                        .WithMany("StudySessions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudyPlatform.Api.Models.Student", "Student")
                        .WithMany("StudySessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.FillBlankActivity", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Attempts");

                    b.Navigation("Distractors");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.OrderingActivity", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Activities.RecognitionActivity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Classroom", b =>
                {
                    b.Navigation("ClassroomModules");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Concept", b =>
                {
                    b.Navigation("ActivityAttempts");

                    b.Navigation("Clues");

                    b.Navigation("FillBlankActivities");

                    b.Navigation("Keywords");

                    b.Navigation("OrderingActivities");

                    b.Navigation("Prerequisites");

                    b.Navigation("RecognitionActivities");

                    b.Navigation("RequiredBy");

                    b.Navigation("StudentStates");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Module", b =>
                {
                    b.Navigation("ClassroomModules");

                    b.Navigation("Concepts");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.SessionActivityPresentation", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Student", b =>
                {
                    b.Navigation("ActivityAttempts");

                    b.Navigation("ConceptStates");

                    b.Navigation("StudySessions");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.StudySession", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("LastFreeRecallSuccessStates");

                    b.Navigation("Presentations");
                });

            modelBuilder.Entity("StudyPlatform.Api.Models.Teacher", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
